# 256 colors
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ',xterm-256color:RGB'
set -as terminal-features ',xterm-256color:RGB'

# Remove ctrl + b prefix and set it to ctrl + a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# shell
set -g default-shell /bin/zsh

# split panels binds
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# send prefix to other applications
bind C-a send-prefix

# changing indexing, base 1
set -g base-index 1
set -wg pane-base-index 1
set -g renumber-windows on

# add keybinding to reload .tmux file
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# move like Vim with panels
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panels with vim keys style
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# copy/paste with vim style
set -wg mode-keys vi
unbind [
bind Escape copy-mode
if-shell "[ -n \"$WAYLAND_DISPLAY\" ]" {
    bind-key p run "wl-paste | tmux load-buffer - ; tmux paste-buffer"
    bind-key -T copy-mode-vi v send -X begin-selection
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
    bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "wl-copy"
} {
    bind-key p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"
    bind-key -T copy-mode-vi v send -X begin-selection
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
    bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
}

set -wg monitor-activity on
set -g visual-activity on

# escape time
set -sg escape-time 0

# focus events (for Neovim)
set -g focus-events on

# mouse support
set -g mouse on

# OPTIONS
set -g history-limit 10000

# Status bar on top
set-option -g status-position top

# customizing status bar
set -g status-style fg=green,bg=black

# coloring window status
set -wg window-status-style fg=green
set -wg window-status-current-style fg=blue

# Active pane border is green while the others are white
set -g pane-border-style fg=white
set -g pane-active-border-style fg=green

# message colors
set -g message-style fg=green,bg=black,bright

set -g status-left " #S"
set -g window-status-current-format " #I:#W "
set -g window-status-format "#I:#W"
set -g status-right "#[fg=green]%R  #[fg=green]%d/%m/%y"
set -g status-justify centre
set -g allow-rename off
set -wg automatic-rename off
